FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04

# Set noninteractive mode for apt-get
ENV DEBIAN_FRONTEND=noninteractive


########### ROS2 ##############################################################################
# Install ROS2 Humble
RUN apt-get update && apt-get install -y curl gnupg2 lsb-release
RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null
RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-humble-desktop

RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-humble-desktop

# Install ROS2 packages
RUN apt install -y \
    libopencv-dev \
    libeigen3-dev \
    libgmp-dev \
    libmpfr-dev \
    libboost-all-dev \
    python3-colcon-common-extensions \
    python3-rosdep \
    python3-argcomplete \
    python3-vcstool \
    ros-humble-gazebo-ros-pkgs

# Install ROS2 1.  std.msg 2.grid_map messages and packages
RUN apt-get install -y \
    ros-humble-sensor-msgs \
    ros-humble-rclpy \
    ros-humble-std-msgs \
    ros-humble-geometry-msgs \
    ros-humble-grid-map-msgs \
    ros-humble-grid-map-core \
    ros-humble-grid-map-cv \
    ros-humble-grid-map-ros

RUN rosdep init && rosdep update

# Install additional dependencies for building from source
RUN apt-get install -y \
    ros-humble-cartographer \
    ros-humble-cartographer-ros \
    ros-humble-navigation2 \
    ros-humble-nav2-bringup \
    ros-humble-dynamixel-sdk \
    ros-humble-turtlebot3-msgs 

ENV TURTLEBOT3_MODEL=waffle
ENV ROS_VERSION=2
ENV ROS_DISTRO=humble
################################################################################################

# Preconfigure tzdata
RUN echo "Etc/UTC" > /etc/timezone && \
    ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime && \
    apt-get update && apt-get install -y tzdata && \
    dpkg-reconfigure --frontend noninteractive tzdata

# Install Python
RUN apt-get update && apt-get install -y \
    python3.10 \
    python3-pip \
    git
    

# Install PyTorch
COPY requirements.txt /tmp/requirements.txt
RUN pip3 install -r /tmp/requirements.txt
RUN pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

# Install other Python packages
RUN pip3 install "numpy<2.0"
RUN pip3 install gymnasium
RUN pip3 install cupy-cuda11x scikit-learn
RUN pip3 install 'git+https://github.com/facebookresearch/detectron2.git'


########### ROS1 ##############################################################################
# # Install ROS
# RUN apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
# RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu focal main" > /etc/apt/sources.list.d/ros-latest.list'
# RUN apt-get update && apt-get install -y --no-install-recommends \
#     ros-noetic-desktop-full

# # Install ROS packages
# RUN apt install -y ros-noetic-pybind11-catkin \
#     ros-noetic-grid-map-core ros-noetic-grid-map-msgs ros-noetic-grid-map-ros ros-noetic-grid-map-rviz-plugin \
#     libopencv-dev \
#     libeigen3-dev \
#     libgmp-dev \
#     libmpfr-dev \
#     libboost-all-dev \
#     ros-noetic-turtlebot3-gazebo ros-noetic-turtlebot3-teleop \
#     ros-noetic-ros-numpy

# RUN pip3 install catkin-tools
# ENV TURTLEBOT3_MODEL=waffle
################################################################################################

    

# Misc
RUN apt install -y gedit

# # Global RRT*, Mapping and Travformer
# RUN pip3 install transforms3d
# RUN python3 -c 'import torch;print(torch.__version__);print(torch.version.cuda)'
# RUN pip3 install mmcv==2.2.0 -f https://download.openmmlab.com/mmcv/dist/cu118/torch2.4/index.html
# RUN pip3 install pandas
# RUN apt-get update && \
#     echo "ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true" | debconf-set-selections && \
#     apt-get install -y ttf-mscorefonts-installer && \
#     fc-cache -f -v

# Digit in Mujoco
RUN pip3 install mujoco==3.2.3
RUN apt-get update && apt-get install -y \
    python3-tk \
    psmisc


# #Local Planner
# RUN pip3 install do-mpc[full]
# RUN pip3 install casadi


# # ROS2
# RUN apt install -y curl gnupg2 lsb-release
# RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key | apt-key add -
# RUN sh -c 'echo "deb http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros2-latest.list'
# RUN apt update
# RUN apt install -y ros-foxy-desktop
# RUN source /opt/ros/foxy/setup.bash
# RUN apt install -y python3-colcon-common-extensions python3-rosdep
# RUN rosdep init
# RUN rosdep update
    


